EXPERIENCE_CHOICES = [
    'None',
    '0-1 year',
    '1-2 years',
    '2-3 years',
    '3-4 years',
    '4-5 years',
    '5-10 years',
    '10-15 years',
    '15+ years',
]


LOCATION_CHOICES = [
    "Mumbai",
    "Delhi",
    "Chiplun",
    "Navi Mumbai",
    "Bengaluru",
    "Ahmedabad",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Jaipur",
    "Surat",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Patna",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Vadodara",
    "Firozabad",
    "Ludhiana",
    "Rajkot",
    "Agra",
    "Siliguri",
    "Nashik",
    "Faridabad",
    "Patiala",
    "Meerut",
    "Kalyan-Dombivali",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Dhanbad",
    "Jodhpur",
    "Amritsar",
    "Raipur",
    "Allahabad",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Madurai",
    "Guwahati",
    "Chandigarh",
    "Hubli-Dharwad",
    "Amroha",
    "Moradabad",
    "Gurgaon",
    "Aligarh",
    "Solapur",
    "Ranchi",
    "Jalandhar",
    "Tiruchirappalli",
    "Bhubaneswar",
    "Salem",
    "Warangal",
    "Mira-Bhayandar",
    "Thiruvananthapuram",
    "Bhiwandi",
    "Saharanpur",
    "Guntur",
    "Amravati",
    "Bikaner",
    "Noida",
    "Jamshedpur",
    "Bhilai Nagar",
    "Cuttack",
    "Kochi",
    "Udaipur",
    "Bhavnagar",
    "Dehradun",
    "Asansol",
    "Nanded-Waghala",
    "Ajmer",
    "Jamnagar",
    "Ujjain",
    "Sangli",
    "Loni",
    "Jhansi",
    "Pondicherry",
    "Nellore",
    "Jammu",
    "Belagavi",
    "Raurkela",
    "Mangaluru",
    "Tirunelveli",
    "Malegaon",
    "Gaya",
    "Tiruppur",
    "Davanagere",
    "Kozhikode",
    "Akola",
    "Kurnool",
    "Bokaro Steel City",
    "Rajahmundry",
    "Ballari",
    "Agartala",
    "Bhagalpur",
    "Latur",
    "Dhule",
    "Korba",
    "Bhilwara",
    "Brahmapur",
    "Mysore",
    "Muzaffarpur",
    "Ahmednagar",
    "Kollam",
    "Raghunathganj",
    "Bilaspur",
    "Shahjahanpur",
    "Thrissur",
    "Alwar",
    "Kakinada",
    "Nizamabad",
    "Sagar",
    "Tumkur",
    "Hisar",
    "Rohtak",
    "Panipat",
    "Darbhanga",
    "Kharagpur",
    "Aizawl",
    "Ichalkaranji",
    "Tirupati",
    "Karnal",
    "Bathinda",
    "Rampur",
    "Shivamogga",
    "Ratlam",
    "Modinagar",
    "Durg",
    "Shillong",
    "Imphal",
    "Hapur",
    "Ranipet",
    "Anantapur",
    "Arrah",
    "Karimnagar",
    "Parbhani",
    "Etawah",
    "Bharatpur",
    "Begusarai",
    "New Delhi",
    "Chhapra",
    "Kadapa",
    "Ramagundam",
    "Pali",
    "Satna",
    "Vizianagaram",
    "Katihar",
    "Hardwar",
    "Sonipat",
    "Nagercoil",
    "Thanjavur",
    "Murwara (Katni)",
    "Naihati",
    "Sambhal",
    "Nadiad",
    "Yamunanagar",
    "English Bazar",
    "Eluru",
    "Munger",
    "Panchkula",
    "Raayachuru",
    "Panvel",
    "Deoghar",
    "Ongole",
    "Nandyal",
    "Morena",
    "Bhiwani",
    "Porbandar",
    "Palakkad",
    "Anand",
    "Purnia",
    "Baharampur",
    "Barmer",
    "Morvi",
    "Orai",
    "Bahraich",
    "Sikar",
    "Vellore",
    "Singrauli",
    "Khammam",
    "Mahesana",
    "Silchar",
    "Sambalpur",
    "Rewa",
    "Unnao",
    "Hugli-Chinsurah",
    "Raiganj",
    "Phusro",
    "Adityapur",
    "Alappuzha",
    "Bahadurgarh",
    "Machilipatnam",
    "Rae Bareli",
    "Jalpaiguri",
    "Bharuch",
    "Pathankot",
    "Hoshiarpur",
    "Baramula",
    "Adoni",
    "Jind",
    "Tonk",
    "Tenali",
    "Kancheepuram",
    "Vapi",
    "Sirsa",
    "Navsari",
    "Mahbubnagar",
    "Puri",
    "Robertson Pet",
    "Erode",
    "Batala",
    "Haldwani-cum-Kathgodam",
    "Vidisha",
    "Saharsa",
    "Thanesar",
    "Chittoor",
    "Veraval",
    "Lakhimpur",
    "Sitapur",
    "Hindupur",
    "Santipur",
    "Balurghat",
    "Ganjbasoda",
    "Moga",
    "Proddatur",
    "Srinagar",
    "Medinipur",
    "Habra",
    "Sasaram",
    "Hajipur",
    "Bhuj",
    "Shivpuri",
    "Ranaghat",
    "Shimla",
    "Tiruvannamalai",
    "Kaithal",
    "Rajnandgaon",
    "Godhra",
    "Hazaribag",
    "Bhimavaram",
    "Mandsaur",
    "Dibrugarh",
    "Kolar",
    "Bankura",
    "Mandya",
    "Dehri-on-Sone",
    "Madanapalle",
    "Malerkotla",
    "Lalitpur",
    "Bettiah",
    "Pollachi",
    "Khanna",
    "Neemuch",
    "Palwal",
    "Palanpur",
    "Guntakal",
    "Nabadwip",
    "Udupi",
    "Jagdalpur",
    "Motihari",
    "Pilibhit",
    "Dimapur",
    "Mohali",
    "Sadulpur",
    "Rajapalayam",
    "Dharmavaram",
    "Kashipur",
    "Sivakasi",
    "Darjiling",
    "Chikkamagaluru",
    "Gudivada",
    "Baleshwar Town",
    "Mancherial",
    "Srikakulam",
    "Adilabad",
    "Yavatmal",
    "Barnala",
    "Nagaon",
    "Narasaraopet",
    "Raigarh",
    "Roorkee",
    "Valsad",
    "Ambikapur",
    "Giridih",
    "Chandausi",
    "Purulia",
    "Patan",
    "Bagaha",
    "Hardoi ",
    "Achalpur",
    "Osmanabad",
    "Deesa",
    "Nandurbar",
    "Azamgarh",
    "Ramgarh",
    "Firozpur",
    "Baripada Town",
    "Karwar",
    "Siwan",
    "Rajampet",
    "Pudukkottai",
    "Anantnag",
    "Tadpatri",
    "Satara",
    "Bhadrak",
    "Kishanganj",
    "Suryapet",
    "Wardha",
    "Ranebennuru",
    "Amreli",
    "Neyveli (TS)",
    "Jamalpur",
    "Marmagao",
    "Udgir",
    "Tadepalligudem",
    "Nagapattinam",
    "Buxar",
    "Aurangabad",
    "Jehanabad",
    "Phagwara",
    "Khair",
    "Sawai Madhopur",
    "Kapurthala",
    "Chilakaluripet",
    "Aurangabad",
    "Malappuram",
    "Rewari",
    "Nagaur",
    "Sultanpur",
    "Nagda",
    "Port Blair",
    "Lakhisarai",
    "Panaji",
    "Tinsukia",
    "Itarsi",
    "Kohima",
    "Balangir",
    "Nawada",
    "Jharsuguda",
    "Jagtial",
    "Viluppuram",
    "Amalner",
    "Zirakpur",
    "Tanda",
    "Tiruchengode",
    "Nagina",
    "Yemmiganur",
    "Vaniyambadi",
    "Sarni",
    "Theni Allinagaram",
    "Margao",
    "Akot",
    "Sehore",
    "Mhow Cantonment",
    "Kot Kapura",
    "Makrana",
    "Pandharpur",
    "Miryalaguda",
    "Shamli",
    "Seoni",
    "Ranibennur",
    "Kadiri",
    "Shrirampur",
    "Rudrapur",
    "Parli",
    "Najibabad",
    "Nirmal",
    "Udhagamandalam",
    "Shikohabad",
    "Jhumri Tilaiya",
    "Aruppukkottai",
    "Ponnani",
    "Jamui",
    "Sitamarhi",
    "Chirala",
    "Anjar",
    "Karaikal",
    "Hansi",
    "Anakapalle",
    "Mahasamund",
    "Faridkot",
    "Saunda",
    "Dhoraji",
    "Paramakudi",
    "Balaghat",
    "Sujangarh",
    "Khambhat",
    "Muktsar",
    "Rajpura",
    "Kavali",
    "Dhamtari",
    "Ashok Nagar",
    "Sardarshahar",
    "Mahuva",
    "Bargarh",
    "Kamareddy",
    "Sahibganj",
    "Kothagudem",
    "Ramanagaram",
    "Gokak",
    "Tikamgarh",
    "Araria",
    "Rishikesh",
    "Shahdol",
    "Medininagar (Daltonganj)",
    "Arakkonam",
    "Washim",
    "Sangrur",
    "Bodhan",
    "Fazilka",
    "Palacole",
    "Keshod",
    "Sullurpeta",
    "Wadhwan",
    "Gurdaspur",
    "Vatakara",
    "Tura",
    "Narnaul",
    "Kharar",
    "Yadgir",
    "Ambejogai",
    "Ankleshwar",
    "Savarkundla",
    "Paradip",
    "Virudhachalam",
    "Kanhangad",
    "Kadi",
    "Srivilliputhur",
    "Gobindgarh",
    "Tindivanam",
    "Mansa",
    "Taliparamba",
    "Manmad",
    "Tanuku",
    "Rayachoti",
    "Virudhunagar",
    "Koyilandy",
    "Jorhat",
    "Karur",
    "Valparai",
    "Srikalahasti",
    "Neyyattinkara",
    "Bapatla",
    "Fatehabad",
    "Malout",
    "Sankarankovil",
    "Tenkasi",
    "Ratnagiri",
    "Rabkavi Banhatti",
    "Sikandrabad",
    "Chaibasa",
    "Chirmiri",
    "Palwancha",
    "Bhawanipatna",
    "Kayamkulam",
    "Pithampur",
    "Nabha",
    "Shahabad, Hardoi",
    "Dhenkanal",
    "Uran Islampur",
    "Gopalganj",
    "Bongaigaon City",
    "Palani",
    "Pusad",
    "Sopore",
    "Pilkhuwa",
    "Tarn Taran",
    "Renukoot",
    "Mandamarri",
    "Shahabad",
    "Barbil",
    "Koratla",
    "Madhubani",
    "Arambagh",
    "Gohana",
    "Ladnu",
    "Pattukkottai",
    "Sirsi",
    "Sircilla",
    "Tamluk",
    "Jagraon",
    "AlipurdUrban Agglomerationr",
    "Alirajpur",
    "Tandur",
    "Naidupet",
    "Tirupathur",
    "Tohana",
    "Ratangarh",
    "Dhubri",
    "Masaurhi",
    "Visnagar",
    "Vrindavan",
    "Nokha",
    "Nagari",
    "Narwana",
    "Ramanathapuram",
    "Ujhani",
    "Samastipur",
    "Laharpur",
    "Sangamner",
    "Nimbahera",
    "Siddipet",
    "Suri",
    "Diphu",
    "Jhargram",
    "Shirpur-Warwade",
    "Tilhar",
    "Sindhnur",
    "Udumalaipettai",
    "Malkapur",
    "Wanaparthy",
    "Gudur",
    "Kendujhar",
    "Mandla",
    "Mandi",
    "Nedumangad",
    "North Lakhimpur",
    "Vinukonda",
    "Tiptur",
    "Gobichettipalayam",
    "Sunabeda",
    "Wani",
    "Upleta",
    "Narasapuram",
    "Nuzvid",
    "Tezpur",
    "Una",
    "Markapur",
    "Sheopur",
    "Thiruvarur",
    "Sidhpur",
    "Sahaswan",
    "Suratgarh",
    "Shajapur",
    "Rayagada",
    "Lonavla",
    "Ponnur",
    "Kagaznagar",
    "Gadwal",
    "Bhatapara",
    "Kandukur",
    "Sangareddy",
    "Unjha",
    "Lunglei",
    "Karimganj",
    "Kannur",
    "Bobbili",
    "Mokameh",
    "Talegaon Dabhade",
    "Anjangaon",
    "Mangrol",
    "Sunam",
    "Gangarampur",
    "Thiruvallur",
    "Tirur",
    "Rath",
    "Jatani",
    "Viramgam",
    "Rajsamand",
    "Yanam",
    "Kottayam",
    "Panruti",
    "Dhuri",
    "Namakkal",
    "Kasaragod",
    "Modasa",
    "Rayadurg",
    "Supaul",
    "Kunnamkulam",
    "Umred",
    "Bellampalle",
    "Sibsagar",
    "Mandi Dabwali",
    "Ottappalam",
    "Dumraon",
    "Samalkot",
    "Jaggaiahpet",
    "Goalpara",
    "Tuni",
    "Lachhmangarh",
    "Bhongir",
    "Amalapuram",
    "Firozpur Cantt.",
    "Vikarabad",
    "Thiruvalla",
    "Sherkot",
    "Palghar",
    "Shegaon",
    "Jangaon",
    "Bheemunipatnam",
    "Panna",
    "Thodupuzha",
    "KathUrban Agglomeration",
    "Palitana",
    "Arwal",
    "Venkatagiri",
    "Kalpi",
    "Rajgarh (Churu)",
    "Sattenapalle",
    "Arsikere",
    "Ozar",
    "Thirumangalam",
    "Petlad",
    "Nasirabad",
    "Phaltan",
    "Rampurhat",
    "Nanjangud",
    "Forbesganj",
    "Tundla",
    "BhabUrban Agglomeration",
    "Sagara",
    "Pithapuram",
    "Sira",
    "Bhadrachalam",
    "Charkhi Dadri",
    "Chatra",
    "Palasa Kasibugga",
    "Nohar",
    "Yevla",
    "Sirhind Fatehgarh Sahib",
    "Bhainsa",
    "Parvathipuram",
    "Shahade",
    "Chalakudy",
    "Narkatiaganj",
    "Kapadvanj",
    "Macherla",
    "Raghogarh-Vijaypur",
    "Rupnagar",
    "Naugachhia",
    "Sendhwa",
    "Byasanagar",
    "Sandila",
    "Gooty",
    "Salur",
    "Nanpara",
    "Sardhana",
    "Vita",
    "Gumia",
    "Puttur",
    "Jalandhar Cantt.",
    "Nehtaur",
    "Changanassery",
    "Mandapeta",
    "Dumka",
    "Seohara",
    "Umarkhed",
    "Madhupur",
    "Vikramasingapuram",
    "Punalur",
    "Kendrapara",
    "Sihor",
    "Nellikuppam",
    "Samana",
    "Warora",
    "Nilambur",
    "Rasipuram",
    "Ramnagar",
    "Jammalamadugu",
    "Nawanshahr",
    "Thoubal",
    "Athni",
    "Cherthala",
    "Sidhi",
    "Farooqnagar",
    "Peddapuram",
    "Chirkunda",
    "Pachora",
    "Madhepura",
    "Pithoragarh",
    "Tumsar",
    "Phalodi",
    "Tiruttani",
    "Rampura Phul",
    "Perinthalmanna",
    "Padrauna",
    "Pipariya",
    "Dalli-Rajhara",
    "Punganur",
    "Mattannur",
    "Mathura",
    "Thakurdwara",
    "Nandivaram-Guduvancheri",
    "Mulbagal",
    "Manjlegaon",
    "Wankaner",
    "Sillod",
    "Nidadavole",
    "Surapura",
    "Rajagangapur",
    "Sheikhpura",
    "Parlakhemundi",
    "Kalimpong",
    "Siruguppa",
    "Arvi",
    "Limbdi",
    "Barpeta",
    "Manglaur",
    "Repalle",
    "Mudhol",
    "Shujalpur",
    "Mandvi",
    "Thangadh",
    "Sironj",
    "Nandura",
    "Shoranur",
    "Nathdwara",
    "Periyakulam",
    "Sultanganj",
    "Medak",
    "Narayanpet",
    "Raxaul Bazar",
    "Rajauri",
    "Pernampattu",
    "Nainital",
    "Ramachandrapuram",
    "Vaijapur",
    "Nangal",
    "Sidlaghatta",
    "Punch",
    "Pandhurna",
    "Wadgaon Road",
    "Talcher",
    "Varkala",
    "Pilani",
    "Nowgong",
    "Naila Janjgir",
    "Mapusa",
    "Vellakoil",
    "Merta City",
    "Sivaganga",
    "Mandideep",
    "Sailu",
    "Vyara",
    "Kovvur",
    "Vadalur",
    "Nawabganj",
    "Padra",
    "Sainthia",
    "Siana",
    "Shahpur",
    "Sojat",
    "Noorpur",
    "Paravoor",
    "Murtijapur",
    "Ramnagar",
    "Sundargarh",
    "Taki",
    "Saundatti-Yellamma",
    "Pathanamthitta",
    "Wadi",
    "Rameshwaram",
    "Tasgaon",
    "Sikandra Rao",
    "Sihora",
    "Tiruvethipuram",
    "Tiruvuru",
    "Mehkar",
    "Peringathur",
    "Perambalur",
    "Manvi",
    "Zunheboto",
    "Mahnar Bazar",
    "Attingal",
    "Shahbad",
    "Puranpur",
    "Nelamangala",
    "Nakodar",
    "Lunawada",
    "Murshidabad",
    "Mahe",
    "Lanka",
    "Rudauli",
    "Tuensang",
    "Lakshmeshwar",
    "Zira",
    "Yawal",
    "Thana Bhawan",
    "Ramdurg",
    "Pulgaon",
    "Sadasivpet",
    "Nargund",
    "Neem-Ka-Thana",
    "Memari",
    "Nilanga",
    "Naharlagun",
    "Pakaur",
    "Wai",
    "Tarikere",
    "Malavalli",
    "Raisen",
    "Lahar",
    "Uravakonda",
    "Savanur",
    "Sirohi",
    "Udhampur",
    "Umarga",
    "Pratapgarh",
    "Lingsugur",
    "Usilampatti",
    "Palia Kalan",
    "Wokha",
    "Rajpipla",
    "Vijayapura",
    "Rawatbhata",
    "Sangaria",
    "Paithan",
    "Rahuri",
    "Patti",
    "Zaidpur",
    "Lalsot",
    "Maihar",
    "Vedaranyam",
    "Nawapur",
    "Solan",
    "Vapi",
    "Sanawad",
    "Warisaliganj",
    "Revelganj",
    "Sabalgarh",
    "Tuljapur",
    "Simdega",
    "Musabani",
    "Kodungallur",
    "Phulabani",
    "Umreth",
    "Narsipatnam",
    "Nautanwa",
    "Rajgir",
    "Yellandu",
    "Sathyamangalam",
    "Pilibanga",
    "Morshi",
    "Pehowa",
    "Sonepur",
    "Pappinisseri",
    "Zamania",
    "Mihijam",
    "Purna",
    "Puliyankudi",
    "Shikarpur, Bulandshahr",
    "Umaria",
    "Porsa",
    "Naugawan Sadat",
    "Fatehpur Sikri",
    "Manuguru",
    "Udaipur",
    "Pipar City",
    "Pattamundai",
    "Nanjikottai",
    "Taranagar",
    "Yerraguntla",
    "Satana",
    "Sherghati",
    "Sankeshwara",
    "Madikeri",
    "Thuraiyur",
    "Sanand",
    "Rajula",
    "Kyathampalle",
    "Shahabad, Rampur",
    "Tilda Newra",
    "Narsinghgarh",
    "Chittur-Thathamangalam",
    "Malaj Khand",
    "Sarangpur",
    "Robertsganj",
    "Sirkali",
    "Radhanpur",
    "Tiruchendur",
    "Utraula",
    "Patratu",
    "Vijainagar, Ajmer",
    "Periyasemur",
    "Pathri",
    "Sadabad",
    "Talikota",
    "Sinnar",
    "Mungeli",
    "Sedam",
    "Shikaripur",
    "Sumerpur",
    "Sattur",
    "Sugauli",
    "Lumding",
    "Vandavasi",
    "Titlagarh",
    "Uchgaon",
    "Mokokchung",
    "Paschim Punropara",
    "Sagwara",
    "Ramganj Mandi",
    "Tarakeswar",
    "Mahalingapura",
    "Dharmanagar",
    "Mahemdabad",
    "Manendragarh",
    "Uran",
    "Tharamangalam",
    "Tirukkoyilur",
    "Pen",
    "Makhdumpur",
    "Maner",
    "Oddanchatram",
    "Palladam",
    "Mundi",
    "Nabarangapur",
    "Mudalagi",
    "Samalkha",
    "Nepanagar",
    "Karjat",
    "Ranavav",
    "Pedana",
    "Pinjore",
    "Lakheri",
    "Pasan",
    "Puttur",
    "Vadakkuvalliyur",
    "Tirukalukundram",
    "Mahidpur",
    "Mussoorie",
    "Muvattupuzha",
    "Rasra",
    "Udaipurwati",
    "Manwath",
    "Adoor",
    "Uthamapalayam",
    "Partur",
    "Nahan",
    "Ladwa",
    "Mankachar",
    "Nongstoin",
    "Losal",
    "Sri Madhopur",
    "Ramngarh",
    "Mavelikkara",
    "Rawatsar",
    "Rajakhera",
    "Lar",
    "Lal Gopalganj Nindaura",
    "Muddebihal",
    "Sirsaganj",
    "Shahpura",
    "Surandai",
    "Sangole",
    "Pavagada",
    "Tharad",
    "Mansa",
    "Umbergaon",
    "Mavoor",
    "Nalbari",
    "Talaja",
    "Malur",
    "Mangrulpir",
    "Soro",
    "Shahpura",
    "Vadnagar",
    "Raisinghnagar",
    "Sindhagi",
    "Sanduru",
    "Sohna",
    "Manavadar",
    "Pihani",
    "Safidon",
    "Risod",
    "Rosera",
    "Sankari",
    "Malpura",
    "Sonamukhi",
    "Shamsabad, Agra",
    "Nokha",
    "PandUrban Agglomeration",
    "Mainaguri",
    "Afzalpur",
    "Shirur",
    "Salaya",
    "Shenkottai",
    "Pratapgarh",
    "Vadipatti",
    "Nagarkurnool",
    "Savner",
    "Sasvad",
    "Rudrapur",
    "Soron",
    "Sholingur",
    "Pandharkaoda",
    "Perumbavoor",
    "Maddur",
    "Nadbai",
    "Talode",
    "Shrigonda",
    "Madhugiri",
    "Tekkalakote",
    "Seoni-Malwa",
    "Shirdi",
    "SUrban Agglomerationr",
    "Terdal",
    "Raver",
    "Tirupathur",
    "Taraori",
    "Mukhed",
    "Manachanallur",
    "Rehli",
    "Sanchore",
    "Rajura",
    "Piro",
    "Mudabidri",
    "Vadgaon Kasba",
    "Nagar",
    "Vijapur",
    "Viswanatham",
    "Polur",
    "Panagudi",
    "Manawar",
    "Tehri",
    "Samdhan",
    "Pardi",
    "Rahatgarh",
    "Panagar",
    "Uthiramerur",
    "Tirora",
    "Rangia",
    "Sahjanwa",
    "Wara Seoni",
    "Magadi",
    "Rajgarh (Alwar)",
    "Rafiganj",
    "Tarana",
    "Rampur Maniharan",
    "Sheoganj",
    "Raikot",
    "Pauri",
    "Sumerpur",
    "Navalgund",
    "Shahganj",
    "Marhaura",
    "Tulsipur",
    "Sadri",
    "Thiruthuraipoondi",
    "Shiggaon",
    "Pallapatti",
    "Mahendragarh",
    "Sausar",
    "Ponneri",
    "Mahad",
    "Lohardaga",
    "Tirwaganj",
    "Margherita",
    "Sundarnagar",
    "Rajgarh",
    "Mangaldoi",
    "Renigunta",
    "Longowal",
    "Ratia",
    "Lalgudi",
    "Shrirangapattana",
    "Niwari",
    "Natham",
    "Unnamalaikadai",
    "PurqUrban Agglomerationzi",
    "Shamsabad, Farrukhabad",
    "Mirganj",
    "Todaraisingh",
    "Warhapur",
    "Rajam",
    "Urmar Tanda",
    "Lonar",
    "Powayan",
    "P.N.Patti",
    "Palampur",
    "Srisailam Project (Right Flank Colony) Township",
    "Sindagi",
    "Sandi",
    "Vaikom",
    "Malda",
    "Tharangambadi",
    "Sakaleshapura",
    "Lalganj",
    "Malkangiri",
    "Rapar",
    "Mauganj",
    "Todabhim",
    "Srinivaspur",
    "Murliganj",
    "Reengus",
    "Sawantwadi",
    "Tittakudi",
    "Lilong",
    "Rajaldesar",
    "Pathardi",
    "Achhnera",
    "Pacode",
    "Naraura",
    "Nakur",
    "Palai",
    "Morinda, India",
    "Manasa",
    "Nainpur",
    "Sahaspur",
    "Pauni",
    "Prithvipur",
    "Ramtek",
    "Silapathar",
    "Songadh",
    "Safipur",
    "Sohagpur",
    "Mul",
    "Sadulshahar",
    "Phillaur",
    "Sambhar",
    "Prantij",
    "Nagla",
    "Pattran",
    "Mount Abu",
    "Reoti",
    "Tenu dam-cum-Kathhara",
    "Panchla",
    "Sitarganj",
    "Pasighat",
    "Motipur",
    "O' Valley",
    "Raghunathpur",
    "Suriyampalayam",
    "Qadian",
    "Rairangpur",
    "Silvassa",
    "Nowrozabad (Khodargama)",
    "Mangrol",
    "Soyagaon",
    "Sujanpur",
    "Manihari",
    "Sikanderpur",
    "Mangalvedhe",
    "Phulera",
    "Ron",
    "Sholavandan",
    "Saidpur",
    "Shamgarh",
    "Thammampatti",
    "Maharajpur",
    "Multai",
    "Mukerian",
    "Sirsi",
    "Purwa",
    "Sheohar",
    "Namagiripettai",
    "Parasi",
    "Lathi",
    "Lalganj",
    "Narkhed",
    "Mathabhanga",
    "Shendurjana",
    "Peravurani",
    "Mariani",
    "Phulpur",
    "Rania",
    "Pali",
    "Pachore",
    "Parangipettai",
    "Pudupattinam",
    "Panniyannur",
    "Maharajganj",
    "Rau",
    "Monoharpur",
    "Mandawa",
    "Marigaon",
    "Pallikonda",
    "Pindwara",
    "Shishgarh",
    "Patur",
    "Mayang Imphal",
    "Mhowgaon",
    "Guruvayoor",
    "Mhaswad",
    "Sahawar",
    "Sivagiri",
    "Mundargi",
    "Punjaipugalur",
    "Kailasahar",
    "Samthar",
    "Sakti",
    "Sadalagi",
    "Silao",
    "Mandalgarh",
    "Loha",
    "Pukhrayan",
    "Padmanabhapuram",
    "Belonia",
    "Saiha",
    "Srirampore",
    "Talwara",
    "Puthuppally",
    "Khowai",
    "Vijaypur",
    "Takhatgarh",
    "Thirupuvanam",
    "Adra",
    "Piriyapatna",
    "Obra",
    "Adalaj",
    "Nandgaon",
    "Barh",
    "Chhapra",
    "Panamattom",
    "Niwai",
    "Bageshwar",
    "Tarbha",
    "Adyar",
    "Narsinghgarh",
    "Warud",
    "Asarganj",
    "Sarsod",
]


ROLE_CHOICES = [
    "Labour",
    "Information Technology",
    "Finance",
    "Sales",
    "Marketing",
    "Human Resources",
    "Customer Service",
    "Engineering",
    "Healthcare",
    "Education",
    "Legal",
    "Manufacturing",
    "Retail",
    "Hospitality",
    "Transportation",
    "Construction",
    "Media and Communications",
    "Research and Development",
    "Design",
    "Government and Public Administration",
    "Non-profit and Social Services",
    "Consulting",
    "Real Estate",
    "Energy",
    "Agriculture",
    "Science",
    "Art and Entertainment",
    "Sports and Recreation",
    "Food Service",
    "Fashion",
    "Environment",
    "Quality Assurance",
    "Logistics",
    "Supply Chain Management",
    "Pharmaceutical",
    "Telecommunications",
    "Insurance",
    "Banking",
    "Investment",
    "Accounting",
    "Retail Management",
    "Project Management",
    "Data Science",
    "Cybersecurity",
    "Digital Marketing",
    "Graphic Design",
    "Teaching",
    "Nursing",
    "Software Development",
    "Hardware Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Biotechnology",
    "Medical Research",
    "Legal Counsel",
    "Culinary Arts",
    "Event Planning",
    "Environmental Science",
    "Public Relations",
    "Social Work",
    "Market Research",
    "Sales Management",
    "Customer Support",
    "Product Management",
    "Operations",
    "Business Development",
    "Human Resources Management",
    "Recruiting",
    "Supply Chain",
    "Retail Sales",
    "Digital Media",
    "Journalism",
    "Advertising",
    "Public Policy",
    "Environmental Policy",
    "Healthcare Management",
    "Pharmacy",
    "Dentistry",
    "Veterinary Medicine",
    "Geology",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Music",
    "Acting",
    "Dancing",
    "Illustration",
    "Photography",
    "Film Production",
    "Gaming",
    "Curatorial",
    "Museum",
    "Zoology",
    "Botany",
    "Ecology",
    "Meteorology",
    "Forestry",
    "Astronomy",
    "Astrophysics",
    "Architecture",
    "Interior Design",
    "Urban Planning",
    "Social Media Management",
    "Content Writing",
    "Copywriting",
    "Search Engine Optimization (SEO)",
    "Data Analysis",
    "Business Analysis",
    "Risk Management",
    "Investment Banking",
    "Financial Planning",
    "Mergers and Acquisitions",
    "Fashion Design",
    "Textile Design",
    "Jewelry Design",
    "Product Design",
    "Industrial Design",
    "Environmental Engineering",
    "Petroleum Engineering",
    "Chemical Engineering",
    "Materials Science",
    "Nuclear Engineering",
    "Renewable Energy",
    "Supply Chain Logistics",
    "Inventory Management",
    "E-commerce",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Game Development",
    "Virtual Reality (VR) Development",
    "Augmented Reality (AR) Development",
    "Ethical Hacking",
    "Information Security",
    "Criminal Justice",
    "Forensic Science",
    "Counseling",
    "Therapy",
    "Clinical Psychology",
    "Emergency Medicine",
    "Radiology",
    "Pharmaceutical Research",
    "Biomedical Engineering",
    "Genetic Counseling",
    "Bioinformatics",
    "International Relations",
    "Diplomacy",
    "Foreign Service",
    "Human Rights",
    "Conflict Resolution",
    "Nonprofit Management",
    "Public Health",
    "Epidemiology",
    "Health Informatics",
    "Dietetics",
    "Fitness Training",
    "Yoga Instruction",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Special Education",
    "Curriculum Development",
    "Instructional Design",
    "Agricultural Science",
    "Horticulture",
    "Veterinary Nursing",
    "Wildlife Conservation",
    "Marine Biology",
    "Oceanography",
    "Astronautics",
    "Space Exploration",
    "Robotics",
    "Artificial Intelligence (AI)",
    "Machine Learning",
    "Natural Language Processing (NLP)",
    "Blockchain Technology",
    "Cryptocurrency",
    "Quantum Computing",
    "Neuroscience",
    "Neuropsychology",
    "Astrobiology",
    "Planetary Science",
    "Exoplanet Research",
    "Fine Arts",
    "Sculpture",
    "Ceramics",
    "Printmaking",
    "Creative Writing",
    "Poetry",
    "Screenwriting",
    "Film Editing",
    "Cinematography",
    "Sound Engineering",
    "Game Design",
    "Interior Architecture",
    "Landscape Architecture",
    "Naval Architecture",
    "Virtual Set Design",
]


DEPARTMENT_CHOICES = [
    "Labour",
    "Accounting",
    "Administration",
    "Advertising",
    "Audit",
    "Business Development",
    "Client Services",
    "Communications",
    "Compliance",
    "Content Management",
    "Customer Success",
    "Data Analysis",
    "Engineering",
    "Facilities",
    "Human Resources",
    "Information Technology",
    "Legal",
    "Logistics",
    "Manufacturing",
    "Marketing",
    "Operations",
    "Product Management",
    "Project Management",
    "Public Relations",
    "Quality Assurance",
    "Research and Development",
    "Sales",
    "Supply Chain",
    "Training and Development",
    "User Experience",
    "Vendor Management",
    "Web Development",
    "Architecture",
    "Customer Support",
    "Design",
    "E-commerce",
    "Environmental Health and Safety",
    "Event Planning",
    "Graphic Design",
    "Healthcare",
    "Hospitality",
    "Insurance",
    "Inventory Management",
    "Investor Relations",
    "Linguistics",
    "Market Research",
    "Merchandising",
    "Nonprofit",
    "Nursing",
    "Operations Management",
    "Payroll",
    "Pharmaceuticals",
    "Procurement",
    "Psychology",
    "Public Health",
    "Real Estate",
    "Retail",
    "Risk Management",
    "Social Media",
    "Software Development",
    "Strategic Planning",
    "Telecommunications",
    "Video Production",
    "Client Relations",
    "Client Acquisition",
    "Media Relations",
    "Customer Engagement",
    "Customer Acquisition",
    "Customer Retention",
    "Business Intelligence",
    "Market Analysis",
    "Financial Analysis",
    "Data Science",
    "Data Engineering",
    "Data Governance",
    "Data Warehousing",
    "Machine Learning",
    "Artificial Intelligence",
    "Robotics",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Automotive Engineering",
    "Materials Science",
    "Logistics and Supply Chain Management",
    "Inventory Control",
    "Quality Control",
    "Production Planning",
    "Operations Research",
    "Environmental Compliance",
    "Occupational Health and Safety",
    "Regulatory Affairs",
    "Employee Relations",
    "Talent Acquisition",
    "Compensation and Benefits",
    "Learning and Development",
    "Diversity and Inclusion",
    "Employee Wellness",
    "IT Support",
    "Network Administration",
    "Cybersecurity",
    "Cloud Computing",
    "Web Development",
    "Software Testing",
    "Front-End Development",
    "Back-End Development",
    "Database Administration",
    "Legal Counsel",
    "Intellectual Property",
    "Contracts Management",
    "Corporate Law",
    "Mergers and Acquisitions",
    "Environmental Law",
    "Criminal Law",
    "Civil Litigation",
    "Family Law",
    "Immigration Law",
    "Patent Law",
    "Trademark Law",
    "Real Estate Law",
    "Logistics and Transportation",
    "Warehouse Management",
    "Distribution",
    "Freight and Shipping",
    "Manufacturing Operations",
    "Quality Management",
    "Plant Operations",
    "Production Control",
    "Marketing Strategy",
    "Market Planning",
    "Digital Marketing",
    "Content Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Brand Management",
    "Event Management",
    "Public Affairs",
    "Community Outreach",
    "Public Policy",
    "Research and Analysis",
    "Product Development",
    "New Product Launch",
    "Product Lifecycle Management",
    "Product Design",
    "Project Planning",
    "Project Execution",
    "Project Monitoring and Control",
    "Project Risk Management",
    "Public Relations",
    "Media Relations",
    "Internal Communications",
    "Crisis Communications",
    "Investor Relations",
    "Product Quality Assurance",
    "Testing and Inspection",
    "Compliance and Regulatory Affairs",
    "New Technology Research",
    "Innovation and Ideation",
    "Sales Strategy",
    "Sales Operations",
    "Sales Support",
    "Channel Management",
    "Retail Management",
    "E-commerce Management",
    "Customer Experience",
    "Customer Service",
    "Technical Support",
    "Client Engagement",
    "Client Acquisition",
    "Client Retention",
    "Market Research Analysis",
    "Market Segmentation",
    "Market Trends Analysis",
    "Market Intelligence",
    "Merchandise Planning",
    "Inventory Control",
    "Merchandise Buying",
    "Nonprofit Management",
    "Fundraising",
    "Donor Relations",
    "Grant Writing",
    "Healthcare Management",
    "Hospital Administration",
    "Healthcare Policy",
    "Pharmaceutical Research",
    "Clinical Trials",
    "Medical Coding",
    "Nursing Administration",
    "Patient Care",
    "Hospitality Management",
    "Hotel Management",
    "Restaurant Management",
    "Tourism Management",
    "Insurance Claims",
    "Underwriting",
    "Risk Assessment",
    "Supply Chain Management",
    "Logistics Coordination",
    "Procurement",
    "Distribution Planning",
    "Training and Development",
    "Employee Training",
    "Leadership Development",
    "Talent Management",
    "User Experience Design",
    "Usability Testing",
    "User Interface Design",
    "Interaction Design",
    "Front-End Web Development",
    "Back-End Web Development",
    "Full-Stack Development",
    "Application Development",
    "Software Engineering",
    "Quality Assurance Testing",
    "Software Deployment",
    "IT Security",
    "Network Security",
    "Cybersecurity Analysis",
    "Cloud Infrastructure Management",
    "Database Management",
    "Legal Advisory",
    "Contract Negotiation",
    "Litigation Support",
    "Intellectual Property Management",
    "Real Estate Management",
    "Property Development",
    "Retail Operations",
    "Visual Merchandising",
    "Loss Prevention",
    "Retail Buying",
    "Retail Planning",
    "Risk Assessment",
    "Environmental Compliance",
    "Occupational Health and Safety",
    "Regulatory Compliance",
    "Employee Relations",
    "Recruitment",
    "Compensation and Benefits Management",
    "Employee Training and Development",
    "Diversity and Inclusion",
    "Employee Wellness",
    "Help Desk Support",
    "IT Infrastructure Management",
    "Network Administration",
    "Cybersecurity Management",
    "Web Development",
    "Mobile App Development",
    "Game Development",
    "Software Testing and Quality Assurance",
    "DevOps",
    "Database Administration",
    "Environmental Health and Safety",
    "Occupational Health",
    "Environmental Compliance",
    "Product Safety",
    "Regulatory Affairs",
    "Performance Management",
    "Employee Engagement",
    "HR Information Systems",
    "Legal Counseling",
    "Corporate Governance",
    "Intellectual Property",
    "Contracts Management",
    "Corporate Litigation",
    "Mergers and Acquisitions",
    "Environmental Law",
    "Criminal Law",
    "Civil Litigation",
    "Family Law",
    "Immigration Law",
    "Patent Law",
    "Trademark Law",
    "Real Estate Law",
    "Criminal Justice",
    "Cybersecurity Law",
    "Corporate Tax Law",
    "Logistics and Transportation",
    "Freight and Shipping",
    "Warehouse Management",
    "Distribution",
    "Fleet Management",
    "Manufacturing Operations",
    "Quality Management",
    "Product Design",
    "Research and Development",
    "Supply Chain Management",
    "Procurement",
    "Materials Management",
    "Quality Control",
    "Project Management",
    "Process Improvement",
    "Safety and Compliance",
    "Facility Management",
    "Marketing Strategy",
    "Market Research",
    "Digital Marketing",
    "Content Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Brand Management",
    "Event Management",
    "Public Relations",
    "Media Relations",
    "Internal Communications",
    "Investor Relations",
    "Product Quality Assurance",
    "Quality Control",
    "Testing and Inspection",
    "Regulatory Affairs",
    "Research and Development",
    "Innovation and Product Development",
    "Research and Analysis",
    "Scientific Research",
    "Data Analysis",
    "Market Analysis",
    "Financial Analysis",
    "Risk Analysis",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Robotics",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Automotive Engineering",
    "Materials Science",
    "Process Engineering",
    "Quality Assurance",
    "Operations Management",
    "Production Control",
    "Plant Management",
    "Inventory Management",
    "Operations Research",
    "Lean Manufacturing",
    "Six Sigma",
    "Occupational Health and Safety",
    "Environmental Compliance",
    "Regulatory Compliance",
    "Facilities Management",
    "Real Estate Management",
    "Property Development",
    "Construction Management",
    "Retail Management",
    "Store Operations",
    "Visual Merchandising",
    "Loss Prevention",
    "Retail Buying",
    "Retail Planning",
    "Fashion Design",
    "Textile Design",
    "Fashion Buying",
    "Fashion Merchandising",
    "Jewelry Design",
    "E-commerce Management",
    "Web Development",
    "Mobile App Development",
    "Software Development",
    "Quality Assurance Testing",
    "User Experience Design",
    "User Interface Design",
    "Graphic Design",
    "Digital Illustration",
    "Video Production",
    "Photography",
    "Print Production",
    "Social Media Management",
    "Community Management",
    "Content Creation",
    "Content Strategy",
    "Email Marketing",
    "SEO (Search Engine Optimization)",
    "SEM (Search Engine Marketing)",
    "Affiliate Marketing",
    "Web Analytics",
    "Video Marketing",
    "Event Planning",
    "Event Coordination",
    "Event Marketing",
    "Event Production",
    "Catering",
    "Hospitality Management",
    "Hotel Management",
    "Restaurant Management",
    "Tourism Management",
    "Culinary Arts",
    "Food and Beverage Management",
    "Insurance Sales",
    "Underwriting",
    "Claims Management",
    "Risk Assessment",
    "Actuarial Science",
    "Policy Administration",
    "Inventory Control",
    "Warehousing",
    "Supply Chain Planning",
    "Demand Forecasting",
    "Procurement",
    "Materials Management",
    "Vendor Management",
    "Quality Control",
    "Manufacturing Operations",
    "Product Design",
    "Quality Assurance",
    "Clinical Research",
    "Pharmaceutical Manufacturing",
    "Biotechnology Research",
    "Laboratory Management",
    "Patient Care",
    "Nursing Administration",
    "Medical Billing",
    "Medical Coding",
    "Healthcare IT",
    "Healthcare Compliance",
    "Healthcare Informatics",
    "Physiotherapy",
    "Occupational Therapy",
    "Speech-Language Pathology",
    "Hospitality Management",
    "Hotel Management",
    "Resort Management",
    "Cruise Ship Management",
    "Travel Agency Management",
    "Tourism Management",
    "Flight Operations",
    "Airline Management",
    "Airport Management",
    "Aircraft Maintenance",
    "Aviation Safety",
    "Pilot Training",
    "Meteorology",
    "Environmental Health and Safety",
    "Industrial Hygiene",
    "Occupational Health",
    "Regulatory Compliance",
    "Risk Management",
    "Emergency Management",
    "Facility Management",
    "Environmental Compliance",
    "Sustainability",
    "Renewable Energy",
    "Occupational Therapy",
    "Physical Therapy",
    "Rehabilitation",
    "Speech-Language Pathology",
    "Behavioral Health",
    "Mental Health Counseling",
    "Psychology",
    "Social Work",
    "Criminal Justice",
    "Law Enforcement",
    "Corrections",
    "Criminology",
    "Forensic Science",
    "Cybersecurity",
    "Network Security",
    "Information Security",
    "Incident Response",
    "Security Analysis",
    "Ethical Hacking",
]


EMPLOYEE_CHOICES = [
    "Full-Time",
    "Part-Time",
    "Contractor",
    "Temporary",
    "Intern",
    "Freelancer",
    "Consultant",
    "Seasonal",
]


APPLICATION_RESPONSE_CHOICES = [
    "None",
    "Interested",
    "Rejected",
    "Shortlisted",
    "Not Selected",
    "Interview Invitation",
    "On-Hold",
    "Pending Review",
    "Overqualified",
    "Underqualified",
    "Selected for Second Round",
    "No Longer Hiring",
    "Considered for Future Opportunities",
]
